### ISSUE TITLE
Exception: I don't have any data to operate with

### ISSUE THREAD

**Issue by frederic-loui** [napalm-automation/napalm-yang#115]
Hi,
Used napalm-yang from standard pip install and faced the [fxp bug](https://github.com/napalm-automation/napalm-yang/issues/89). So switched to napalm-yang develop and get this error:

> No handlers could be found for logger "napalm-yang"
> Traceback (most recent call last):
>   File "./napalm-yang-01.py", line 17, in <module>
>     model.parse_config(device=d,profile=['junos'])
>   File "/home/ansible/playbooks/napalm-yang/napalm_yang/base.py", line 240, in parse_config
>     parser = Parser(v, device=device, profile=profile, native=native, is_config=True)
>   File "/home/ansible/playbooks/napalm-yang/napalm_yang/parser.py", line 48, in __init__
>     raise Exception("I don't have any data to operate with")
> Exception: I don't have any data to operate with
> 

python test script is standard:

```
#! /usr/bin/python

import napalm
import napalm_yang

from pprint import *

driver = napalm.get_network_driver('junos')

model=napalm_yang.base.Root()
model.add_model(napalm_yang.models.openconfig_interfaces)
model.add_model(napalm_yang.models.openconfig_vlan)

#pprint(napalm_yang.utils.model_to_dict(model))

with driver(hostname="gn4-net-core-5", username="<user>", password="<password>) as d:
    model.parse_config(device=d,profile=['junos'])

```

With previous napalm-yang module (0.0.7) , I got:

> No handlers could be found for logger "napalm-yang"
> Traceback (most recent call last):
>   File "./napalm-yang-01.py", line 17, in <module>
>     model.parse_config(device=d,profile=['junos'])
>   File "/home/ansible/playbooks/napalm-yang/napalm_yang/base.py", line 240, in parse_config
>     parser = Parser(v, device=device, profile=profile, native=native, is_config=True)
>   File "/home/ansible/playbooks/napalm-yang/napalm_yang/parser.py", line 48, in __init__
>     raise Exception("I don't have any data to operate with")
> Exception: I don't have any data to operate with
> ansible@gn4-ansible:~/playbooks$ export PYTHONPATH=~/playbooks/napalm-yang/^C
> ansible@gn4-ansible:~/playbooks$ unset PYTHONPATH
> ansible@gn4-ansible:~/playbooks$ ./napalm-yang-01.py    
> No handlers could be found for logger "napalm-yang"
> Traceback (most recent call last):
>   File "./napalm-yang-01.py", line 17, in <module>
>     model.parse_config(device=d,profile=['junos'])
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/base.py", line 225, in parse_config
>     parser.parse()
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 85, in parse
>     self._parse(self._yang_name, self.model, self.mapping[self._yang_name])
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 91, in _parse
>     self._parse_container(attribute, model, mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 132, in _parse_container
>     self._parse(k, v, mapping[v._yang_name])
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 93, in _parse
>     self._parse_list(attribute, model, mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 178, in _parse_list
>     self._parse(key, obj, element_mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 91, in _parse
>     self._parse_container(attribute, model, mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 132, in _parse_container
>     self._parse(k, v, mapping[v._yang_name])
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 91, in _parse
>     self._parse_container(attribute, model, mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 132, in _parse_container
>     self._parse(k, v, mapping[v._yang_name])
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 95, in _parse
>     self._parse_leaf(attribute, model, mapping)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parser.py", line 194, in _parse_leaf
>     value = self.parser.parse_leaf(mapping["_process"], self.bookmarks)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parsers/base.py", line 99, in parse_leaf
>     result = getattr(self, method_name)(m, data)
>   File "/usr/local/lib/python2.7/dist-packages/napalm_yang/parsers/jsonp.py", line 116, in _parse_leaf_map
>     return mapping['map'][v.lower()]
> KeyError: u'fxp'

Thanks for your help !

**Comment by dbarrosop** [comment]
Could you start by testing one model at a time?

```
model=napalm_yang.base.Root()
model.add_model(napalm_yang.models.openconfig_interfaces)
# model.add_model(napalm_yang.models.openconfig_vlan)
```

and then:

```
model=napalm_yang.base.Root()
# model.add_model(napalm_yang.models.openconfig_interfaces)
model.add_model(napalm_yang.models.openconfig_vlan)
```

I want see which one is triggering that error. I suspect it might be a misleading error and the truth is that the `openconfig_vlan` parser is incomplete. For instance, compare these two:

https://github.com/napalm-automation/napalm-yang/tree/develop/napalm_yang/mappings/eos/parsers/config/openconfig-vlan
https://github.com/napalm-automation/napalm-yang/tree/develop/napalm_yang/mappings/junos/parsers/config/openconfig-vlan

Junos only supprts the subinterfaces' vlan-id from the `openconfig-vlan`.

**Comment by frederic-loui** [comment]
Hi, thanks for your very quick reply. My bad I should not have tried to test both model at the same time. :-)
> napalm_yang.models.openconfig_interfaces

works fine !

> napalm_yang.models.openconfig_vlan

trigger the above error: 
`Exception: I don't have any data to operate with`

**Comment by dbarrosop** [comment]
So, yeah, problem as I mentioned is that the profile doesn't really do anything with the `openconfig-vlan` model for junos. You'd have to write it if you need to retrieve vlan information :P

I will leave this one open though to see if I can return a more meaningful error to avoid confusing people.

**Comment by frederic-loui** [comment]
Hi, thanks for pin-pointing the issue. Of course I do not exclude writing a profile in order to retrieve these types of information... I just need to get more familiar with napalm profile framework. (Am still at a noob level :-) ) Thanks again for your quick support !

**Comment by dbarrosop** [comment]
closing this one, feel free to reopen if you still need help with this
