### ISSUE TITLE
Issue parsing ietf-pim

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm-yang#15]
Ran into issues attempting to build models from the draft IETF PIM yang models.  napalm.py is not parsing several keywords correctly:

presence
choice

**Comment by bewing** [comment]
See https://github.com/YangModels/yang/pull/127/commits/e2647145ff6c78a0465253e410f8cd678cea2e8f for the new YANG models that I attempted to parse.

**Comment by dbarrosop** [comment]
Do you need any model in particular or all of them?

**Comment by bewing** [comment]
In order to process pim-sm ASR static RPs, I believe we need to parse pim-base, pim-sm, and pim-rp.  Further can of worms -- network instance/vrf is up the tree in routing-protocols, so may need to parse that as well. :/

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
