### ISSUE TITLE
subinterface name in Junos

### ISSUE THREAD

**Issue by ckishimo** [napalm-automation/napalm-yang#150]
I have a question regarding the subinterface name in Junos. 
I can see a subinterface name is just the `index`
```
            "ge-0/0/0": {
                "config": {
                    "enabled": true,
                    "name": "ge-0/0/0",
                    "type": "ethernetCsmacd"
                },
                "name": "ge-0/0/0",
                "subinterfaces": {
                    "subinterface": {
                        "0": {
                            "config": {
                                "description": "R1@ge-0/0/0.0->R2-ge-0/0/0.0",
                                "enabled": true,
                                "name": "0"    <===== ***
                            },
```
I was wondering if the name should include the parent interface like:
```
                "subinterfaces": {
                    "subinterface": {
                        "0": {
                            "config": {
                                "description": "R1@ge-0/0/0.0->R2-ge-0/0/0.0",
                                "enabled": true,
                                "name": "ge-0/0/0.0"   <===== ***
                            },
```
In EOS and IOS the subinterface names contains the parent interface name
```
                "subinterfaces": {
                    "subinterface": {
                        "1": {
                            "config": {
                                "description": "another subiface",
                                "enabled": true,
                                "name": "GigabitEthernet2.1" 
                "subinterfaces": {
                    "subinterface": {
                        "1": {
                            "config": {
                                "description": "another subiface",
                                "enabled": false,
                                "name": "Ethernet2.1"    
```
Could anyone confirm which is the correct output ? thanks

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
