### ISSUE TITLE
Parsing network statement in ospf

### ISSUE THREAD

**Issue by yapengwu** [napalm-automation/napalm-yang#157]
Trying to parsing ios configuration, ospf configuration is as following:
```
router ospf 65003
 router-id 192.168.0.3
 passive-interface Loopback0
 network 10.1.0.4 0.0.0.3 area 0
 network 10.1.0.8 0.0.0.3 area 1.2.3.4
 network 10.1.0.16 0.0.0.3 area 1.2.3.4
 network 192.168.0.3 0.0.0.0 area 0
```
In the parser, we need to use IP address and mask fields to find out which interface is. 

We need to find a solution to support this.

**Comment by dbarrosop** [comment]
The problem I see with this is that we need to be able parse the configuration into the an instance of the model and then we need to be able to regenerate the configuration the same configuration from such instance. You may be able to add some magic to translate that into actual interfaces but then it's going to be impossible from that model to get back to this configuration. IMO, we should parse the are from the configuration at the interface level as explained here:

https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_ospf/configuration/xe-3s/iro-xe-3s-book/iro-mode-ospfv2.html#GUID-E447655F-8A15-456A-86FE-3A21D1AE55A1

Does this make sense?

**Comment by yapengwu** [comment]
interface level configuration is better. Can you share some insight about parsing rule in this case? 
I think I need to parse the area and also interfaces associate with that area.

**Comment by dbarrosop** [comment]
If you are using interface-level configuration you should be able to extra the area and interface details directly from the interfaces. To do that you will have to use the `from: root_network_instances.0` to go back to the root of the configuration. If you open a PR with a test case (ie https://github.com/napalm-automation/napalm-yang/tree/develop/test/integration/test_profiles/ios/openconfig-interfaces/config/default) I can help you with it.

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
