### ISSUE TITLE
fetching interface config when using groups on Junos

### ISSUE THREAD

**Issue by ghost** [napalm-automation/napalm-yang#163]
Hi, 
not sure if you have noticed already, but the following rpc command seems to be more efficient than <get-configuration/>' , specially when you use groups as we do.

junos/parsers/config/openconfig-interfaces
interfaces.yaml
metadata:                                                                      
    processor: XMLParser                                                       
    execute:                                                                   
        - method: _rpc                                                         
          kwargs:                                                              
              get: '\<get-configuration inherit="inherit"\> \</get-configuration\>'

BR
Al

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
