### ISSUE TITLE
requirements.txt format breaks my conda version

### ISSUE THREAD

**Issue by raddessi** [napalm-automation/napalm-yang#164]
The format pyangbind>=0.8.0<1.0.0 seems to cause a parsing error, I believe pyangbind>=0.8.0,<1.0.0 is expected. I've tested locally and this seems to fix my issue, PR inbound :)

**Comment by raddessi** [comment]
FYI, conda version 4.6.1 and pip version 19.0.1

**Comment by dbarrosop** [comment]
Thanks!
