### ISSUE TITLE
Adding VLAN members

### ISSUE THREAD

**Issue by gladpark** [napalm-automation/napalm-yang#169]
Hello, 

I'm trying to add members to a VLAN object, but I seem to be getting some strange output. 

When I trying to add an interface as a member of VLAN I get a number like 'dea3a1ac-4eb9-11e9-a300-000c29507a90'. I don't know what it means. Maybe I'm not ment to add members like this? 

Example below. 
Thank you. 

```
>>> yang_device = napalm_yang.base.Root()
>>>
>>> yang_device.add_model(napalm_yang.models.openconfig_vlan())
>>>
>>> vlan = yang_device.vlans.vlan.add("Vlan101")
>>>
>>> pprint(yang_device.get(filter=True))
{'vlans': {'vlan': OrderedDict([('Vlan101', {'vlan-id': 'Vlan101'})])}}
>>>
>>> vlan.members.member.add("Gig1/0/1")
'dea3a1ac-4eb9-11e9-a300-000c29507a90'
>>>
>>> pprint(yang_device.get(filter=True))
{'vlans': {'vlan': OrderedDict([('Vlan101',
                                 {'members': {'member': OrderedDict([('dea3a1ac-4eb9-11e9-a300-000c29507a90',
                                                                      {})])},
                                  'vlan-id': 'Vlan101'})])}}
```

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
