### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-yang#2]
See details in the parent issue napalm-automation/napalm#199

**Comment by xavierhardy** [comment]
The parent issue is closed and `napalm-yang` is now Python-3 compatible and nothing stands out in the output of `2to3`. Shouldn't it be closed then or am I missing something?

**Comment by dbarrosop** [comment]
yes, you are right. Thanks for the reminder. For reference, travis tests using py3.6 are enabled here:

https://github.com/napalm-automation/napalm-yang/blob/develop/.travis.yml#L4
