### ISSUE TITLE
Allow pure python parsers for complex models

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-yang#54]
Or when the device does not have capabilities to retrieve the operational data in a bulk.
They can also exist as a private method under the drivers, but we have agreed that we could investigate this alternative to avoid a dependency loop.

**Comment by dbarrosop** [comment]
Closing as this can already be done. Or did you want to discuss something? Feel free to reopen if it's the case.

**Comment by mirceaulinic** [comment]
Yeah, I'd like to reopen, but I don't have rights under this organization...

**Comment by dbarrosop** [comment]
Sure, reopening but for what reason?

**Comment by mirceaulinic** [comment]
For the reasoning we have agreed few days ago... complex cases where you need more interaction with the device. We discussed together and identified edge cases where currently would be hard to use the existing DSL.

**Comment by mirceaulinic** [comment]
Absolutely not an urgent task, but please let's leave this open. I'd be happy to provide a solution for this.

**Comment by dbarrosop** [comment]
Yes, but this can be done already. You just need to call from the DSL your private method and do a 1:1 mapping from the data returned to the yang models. Well, we will need to merge this #38

**Comment by dbarrosop** [comment]
It's also the same discussion being tracked in #39

**Comment by mirceaulinic** [comment]
Correct, it can be done through a private method. That implies:

1. One or more drivers have the private method for a method, which implies synchronization, while the DSL lives in one single place.
2. (1) implies another release loop: the driver waits to napalm-yang to release the parsers & translators for a model, which waits for the driver to be released with the private method.

This is just an improvement. Do you think it would be detrimental to have everything straight forward and clean?

**Comment by dbarrosop** [comment]
We could have a sort of "preprocessor' and just call the `cli` method and run the response through it before getting the data into the parser. That would be an alternative to my proposal that would solve your release cycle concern but it will be less flexible as that means you can only rely on well known methods (which is probably fine so it doesn't really worry me).

**Comment by dbarrosop** [comment]
Unfortunately I don't have the cycles to keep maintaining this project so as of now it's officially abandoned. If someone wants to fork the project and maintain it don't hesitate to contact me to add a link to the fork and direct existing and new users to the new fork. However, I'd recommend checking the following alternative:

* [yangify](https://github.com/networktocode/yangify)

Yangify has a cleaner interface that is easier to maintain and happens to be orders of magnitude faster and also more memory efficient.

If you are an existing user of napalm-yang and are worried about this announcement and/or want help migrating to some other project don't hesitate to contact me.
