### ISSUE TITLE
XMLParser Leaf map is missing default argument

### ISSUE THREAD

**Issue by matejv** [napalm-automation/napalm-yang#55]
Can we get a default attribute supported for `mode: map` in [XMLParser](https://github.com/napalm-automation/napalm-yang/blob/dbarrosop/include/docs/yang/parsers/XMLParser.rst#leaf---map)? TextParser has it :)

**Comment by matejv** [comment]
Ah, I miss-understood how the default argument behaves.

Value set with argument `default` will be used if regex does not match anything. Then that value is looked up in `map` argument.

I thought that `default` argument is the value returned if the value matched by `regex` is not defined in `map` argument OR when `regex` does not match. That would make more sense to me. What do you think?

I wanted to set default interface type for "weird" interfaces. Can't do that with current behaviour - it will crash with KeyError. Meanwhile looked deeper into my Juniper switch and noticed I need to only add one or two types to `map`.

**Comment by dbarrosop** [comment]
> I thought that default argument is the value returned if the value matched by regex is not defined in map argument OR when regex does not match

Not so sure about that. Usually the map is going to be trying to assign a value to an enumeration field so having a "default" value feels like something that is going probably to assign the wrong value to the field. I'd rather fail, have the issue reported and fix it. For example, let's say I am testing on my lab an interface parser for junos and everything I have configured is a `ge` and an `ae` interface and I default everything else to some particular type. If you have `xe`, `tun` or other type of interfaces in your network they are going to be assigned silently to the "default" type, which is clearly wrong.

I am not saying there are no cases where a default value as you describe might be useful but I don't think the interface case is one of them at least.

What do you think?

**Comment by matejv** [comment]
OK, that argument makes sense. Let's keep that current behaviour for now. Expect a pull request for a bunch of interface types in the next few days :)

**Comment by dbarrosop** [comment]
Great! Will close this one down. We can revisit your feature request in the future as there might be some case where it makes sense. For the moment though I prefer to implement features we know we need :)
