### ISSUE TITLE
RTD link is invalid

### ISSUE THREAD

**Issue by jwbensley** [napalm-automation/napalm-yang#79]
Hi guys,

The RTD link in the repo README points to a non-existing URL, looks like it should be: 

http://napalm.readthedocs.io/en/latest/yang.html

**Comment by dbarrosop** [comment]
Good catch, I will fix shortly. The documentation right now is vastly outdated as we have refactored lots of stuff trying to make the parser simpler to use. Hopefully I will remediate that this week or next once PR #76 is merged.
